name: event_prokit
description: A new Flutter project.
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Base
  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.4
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  qr_flutter: ^4.0.0 
  url_launcher: ^6.0.10
  chapasdk: ^0.0.7+1
  google_sign_in: ^6.2.1
  country_pickers: ^2.0.0
  shared_preferences: ^2.0.11
  confetti: ^0.7.0
  screenshot: ^2.5.0
  qr_code_scanner: ^1.0.1


  # Event
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.5.0
  pointycastle: ^3.7.3

dependency_overrides:
  intl: ^0.18.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - images/