name: event_prokit
description: A new Flutter project.
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Base
  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.4
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  qr_flutter: ^4.0.0 
  url_launcher: ^6.0.10
  chapasdk: ^0.0.7+1
  google_sign_in: ^6.2.1
  country_pickers: ^2.0.0
  shared_preferences: ^2.0.11
  confetti: ^0.7.0
  screenshot: ^2.5.0
  qr_code_scanner: ^1.0.1
  timeago: ^3.0.0
  fluttertoast: ^8.2.2
  uni_links: ^0.5.1
  socket_io_client: ^2.0.3
  image_picker: ^1.1.2
  video_player: ^2.8.1
  shimmer: ^3.0.0
  animate_do: ^3.3.4
  flutter_staggered_grid_view: ^0.7.0
  youtube_player_flutter: ^9.0.3
  barcode_widget: ^2.0.4
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
 
  
  

  # Event
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.5.0
  pointycastle: ^3.7.3

dependency_overrides:
  intl: ^0.18.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - images/